### ISSUE TITLE
Ошибка в формуле см. методичку

### ISSUE THREAD

**Issue by AleksandrRybin** [SqrtMinusOne/Digital_Signal_Processing#1]
https://github.com/SqrtMinusOne/Digital_Signal_Processing/blob/8731a9b6bc60d9a369a891f583a14da55a9a5daa/0_data.py#L15

**Comment by SqrtMinusOne** [comment]
Исправлено: f1a266d5418aef9c2c251f4e94ee4e40836f4aef
