### ISSUE TITLE
Ещё ошибка в формуле, а также в следующих двух

### ISSUE THREAD

**Issue by AleksandrRybin** [SqrtMinusOne/Digital_Signal_Processing#2]
https://github.com/SqrtMinusOne/Digital_Signal_Processing/blob/8731a9b6bc60d9a369a891f583a14da55a9a5daa/0_data.py#L23

**Comment by SqrtMinusOne** [comment]
Исправлено: f1a266d5418aef9c2c251f4e94ee4e40836f4aef
